/*jshint node:true, indent:2, curly:false, eqeqeq:true, immed:true,
latedef:true, newcap:true, noarg:true, regexp:true, undef:true,
strict:true, trailing:true, white:true */
/*global XT:true */

String.toLocaleString({
  "en-us": {
    "%year": "Year",
    "%wonOpportunities": "Opportunities Won",
    "%trailing12": " Trailing 12",
    "%toplistTrailingShipments": "Shipments, Profit Top List",
    "%toplistTrailingQuoteActive": "Active Quotes Top List",
    "%toplistTrailingQuote": "Quotes Top List",
    "%toplistTrailingOpportunityActive": "Active Opportunities Top List",
    "%toplistTrailingOpportunity": "Opportunities Top List",
    "%toplistTrailingBooking": "Sales Top List",
    "%toplistTrailingBacklog": "Backlog Top List",
    "%toplistTrailing12": "Top List Trailing 12",
    "%targetedOpportunities": "Targeted Opportunities",
    "%staleAnalysisWarning": "Free trial demo analysis data will not be updated from your live changes.",
	"%SOByPeriod": "Oustanding Orders By Period",
	"%SOOrder": "Sales Orders",
	"%SODelivery": "Deliveries",
    "%shipRegion": "Shipping Region",
    "%shipmentsTrailing": "Shipments-Profit",
    "%shipmentsMapTrailing": "Shipments City Map",
    "%shipment": "Shipment",
    "%salesVelocity": "Sales Velocity",
    "%salesRep": "Sales Rep",
	"%sales": "Sales",
    "%ratioConversionWeighted": "Opporunity Conversion Weighted Ratio",
    "%ratioConversion": "Opportunity Conversion Ratio",
    "%quotesTrailing": "Quotes",
    "%quotesMapTrailing": "Quotes City Map",
    "%quotesActiveTrailing": "Active Quotes",
    "%quotesActiveMapTrailing": "Active Quotes City Map",
    "%productCategory": "Item Category",  // really itemCategory
    "%previousYear": "Previous Year",
    "%periodEnding": "Period Ending",
    "%percentProbabilityOpportunity": "Opportunity Probability",
    "%percentOpportunityForecastProbability": "Opportunity Forecast Probability",
    "%percentForecastProbability": "Forecast Probability",
    "%percentageMargin": "Shipment Margin",
    "%opportunityQuoteBookingFunnel": "Sales Funnel, sum for trailing 12 months",
    "%opportunityForecastTrailing": "Opportunity Forecast",
    "%opportunity": "Opportunity",
    "%opportunitiesTrailing": "Opportunities",
    "%opportunitiesStateMapTrailing": "Opportunities State Map",
    "%opportunitiesMapTrailing": "Opportunities City Map",
    "%opportunitiesFunnel": "Opportunity Pipeline",
    "%opportunitiesBookingsTrailing": "Opportunity Conversion",
    "%opportunitiesActiveNext": "Opportunities Next 6 months",
    "%opportunitiesActiveMapTrailing": "Active Opportunities City Map",
    "%OpenStreetMap.Mapnik": "OSM Mapnik",
    "%OpenMapSurfer.Roads": "OMS Roads",
    "%next6Months": "Next 6 Months",
    "%next3Months": "Next 3 Months",
    "%month": "Month",
    "%measureName": "Measure Name",
    "%measure": "Measure",
    "%maps": "Maps",
    "%MapQuestOpen.OSM": "MQO OSM",
    "%lineChart": "Line Chart",
    "%itemType": "Item Type",
    "%item": "Item",
    "%interestB2SImpact": "Backlog Impact",
    "%HERE.normalDay": "HERE Normal Day",
	"%fullfillment": "Fullfillment & Profitability",
	"%financials": "Financials",
    "%endPeriod": "Ending Period",
    "%ending": " ending ",
    "%dimension": "Dimension",
    "%daysStartToTarget": "Opportunity Start to Target",
    "%daysStartToAssigned": "Opportunity Start to Assigned",
    "%daysStartToActual": "Opportunity Start to Actual",
    "%daysBookingToShipment": "Booking to Shipment Days",
    "%current": "Current",
	"%CRQuote": "Quotes",
	"%CROpportunityForecast": "Opportunity Forecast",
	"%CROpportunityAndOrder": "Opportunities & Orders",
	"%CROpportunity": "Opportunities",
	"%crm": "Customer Relationship Management",
    "%countShipments": "Shipment Count",
    "%countQuotes": "Quote Count",
    "%countOpportunities": "Opportunity Count",
    "%countForecastOpportunities": "Opportunity Forecast Count",
    "%countBookings": "Booking Count",
    "%countBacklog": "Backlog Booking Count",
    "%count": "Count",
    "%convertedQuotes": "Converted Quotes",
    "%classCode": "Item Class",  // really itemClass
    "%chooseMeasure": "Choose Measure",
    "%chooseDimensionMeasure": "Choose Dimension and Measure",
    "%chartType": "Chart Type",
    "%chartFilters": "Chart Filters",
    "%bubbleChart": "Bubble Chart",
    "%bookingsTrailing": "Sales Orders",
    "%bookingsMapTrailing": "Sales Orders City Map",
    "%booking": "Booking",
    "%billRegion": "Billing Region",
    "%barChart": "Bar Chart",
    "%balanceBacklog": "Backlog Balance",
    "%backlogTrailing": "Backlog",
    "%backlogMapTrailing": "Backlog City Map",
    "%averageQuote": "Quote Average",
    "%averageOpportunityWeighted": "Opportunity Weighted  Average",
    "%averageOpportunity": "Opportunity  Average",
    "%averageBooking": "Booking Average",
    "%average": "Average",
    "%assignedOpportunities": "Assigned Opportunities",
    "%areaChart": "Area Chart",
    "%analysis": "Analysis",
    "%amountShipmentDiscount": "Shipment Discount",
    "%amountShipment": "Shipment Amount",
    "%amountQuoteDiscount": "Quote Discount",
    "%amountQuote": "Quote Amount",
    "%amountProfit": "Shipment Profit",
    "%amountOpportunityWeighted": "Opportunity Weighted",
    "%amountOpportunityForecastWeighted": "Opportunity Forecast Weighted",
    "%amountOpportunityForecast": "Opportunity Forecast",
    "%amountOpportunity": "Opportunity Amount",
    "%amountCost": "Shipment Cost",
    "%amountBookingDiscount": "Booking Discount",
    "%amountBooking": "Booking Amount",
    "%amount": "Amount",
    "%allQuotes": "All Quotes",
    "%allOpportunities": "All Opportunities",
    "%allBookings": "All Bookings",
    "%actualOpportunities": "Actual Opportunities",
    "%active": "Active ",
  }
 });
